FloodedRoadKiyose/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
	path('ac01/', include('ac01.urls')),
	path('ac02/', include('ac02.urls')),
]

# 開発サーバーでメディアを配信できるようにする
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ac01/urls.py
from django.urls import path
from ac01 import views

app_name = 'ac01'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('sc0101', views.Sc0101View.as_view(), name="sc0101"),
    path('sc0102', views.Sc0102View.as_view(), name="sc0102"),
    path('sc0104', views.Sc0104View.as_view(), name="sc0104"),
]

ac01/models.py
from django.db import models
from django.core.files.storage import FileSystemStorage


# 抽象クラス（作成日時、更新日時を持つクラス）
class DatedModel(models.Model):
	create_time = models.DateTimeField(auto_now_add=True)
	update_time = models.DateTimeField(auto_now=True)

	class Meta:
		abstract = True


# 丁目マスタ（MST_CHOME）
class Chome(models.Model):
	id = models.DecimalField(primary_key=True, max_digits=4, decimal_places=0)
	chome = models.TextField()


# 分類テーブル（TBL_CATEGORY）
class Category(models.Model):
	category_cd = models.DecimalField(primary_key=True, max_digits=10, decimal_places=0)
	category = models.CharField(blank=True, max_length=64)

	def __str__(self):
		return self.category


# 会員テーブル（TBL_MEMBER）
class Member(models.Model):
	member_no = models.DecimalField(primary_key=True, max_digits=10, decimal_places=0)
	member_name = models.CharField(blank=True, max_length=64)
	mail = models.CharField(blank=True, max_length=128)
	tel = models.CharField(blank=True, max_length=13)
	manager_flg = models.CharField(blank=True, max_length=1)
	password = models.CharField(blank=True, max_length=128)


# 冠水状況画像テーブル（TBL_PHOTO）
class Photo(models.Model):
	id = models.DecimalField(primary_key=True, max_digits=10, decimal_places=0)
	code = models.DecimalField(null=True, max_digits=10, decimal_places=0)
	dtime = models.DecimalField(max_digits=12, decimal_places=0)
	chome = models.ForeignKey(Chome, on_delete=models.CASCADE, related_name='states')
	detail = models.CharField(blank=True, max_length=64)
	member_no = models.DecimalField(max_digits=10, decimal_places=0)
	category_cd = models.DecimalField(max_digits=10, decimal_places=0, default=0)
	photo = models.ImageField(storage=FileSystemStorage())

	@property
	def data_time(self):
		s0 = self.dtime
		yy = int(s0 // 100000000)
		s0 = s0 % 100000000
		mm = int(s0 // 1000000)
		s0 = s0 % 1000000
		dd = int(s0 // 10000)
		s0 = s0 % 10000
		hr = int(s0 // 100)
		mn = int(s0 % 100)
		print(type(yy))
		print("Photo.data_time - ", yy, mm, dd, hr, mn)
		s1 = '{:04d}/{:02d}/{:02d} {:02d}:{:02d}'.format(yy, mm, dd, hr, mn)
		return s1

ac01/forms.py
import logging
from datetime import datetime
from django import forms
from ac01.models import *
from ac01.query import has_member_no

dTimeFormatter = "{0:%Y/%m/%d} {0:%H:%M:%S}"

# 時刻プルダウンリスト選択肢
class SelTime:
	pass


# メニュー画面フォーム
class Sc0101Form(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.function_cd = "00"
        self.op_time = dTimeFormatter.format(datetime.now())

    def clean(self):
        #logging.debug("Sc0101Form" + " - clean=" + self.cleaned_data['function_cd'])
        #function_cd = self.cleaned_data['function_cd']
        #if function_cd != "01" and function_cd != "02":
        #    raise forms.ValidationError('メニューを選択して下さい。')
        return self.cleaned_data


# 画像登録フォーム
class Sc0102Form(forms.ModelForm):
    entryTime = forms.DateTimeInput()

    class Meta:
        model = Photo
        fields = ['code', 'dtime', 'chome', 'detail', 'member_no', 'photo']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.function_cd = "99"
        self.op_time = dTimeFormatter.format(datetime.now())
        #print(self.op_time)
        self.data_time = self.op_time.replace("/", "").replace(" ", "").replace(":", "")[0:11] + "0"
        self.sel_time_list = list()
        for hh in range(0, 24):
            for mm in range(0, 60, 10):
                sel_time = SelTime()
                sel_time.txt : str = '{:02d}:{:02d}'.format(hh, mm)
                sel_time.val = '{:02d}{:02d}'.format(hh, mm)
                self.sel_time_list.append(sel_time)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})

    def clean(self):
        try:
            photo = self.cleaned_data['photo']
            if photo:
                pass
            else:
                self.add_error('photo', '画像が選択されていません。')
        except (KeyError, ValueError):
            self.add_error('photo', '画像が選択されていません。')
        return self.cleaned_data

    def clean_member_no(self):
        member_no = self.cleaned_data['member_no']

        if has_member_no(int(member_no)):
            pass
        else:
            raise forms.ValidationError('会員番号が不適切です。')

        return member_no

    def save(self, commit=False):
        state = super().save(commit)
        state.code = str(self.cleaned_data['code'])
        print("Sc0102Form.save - state:", state)
        state.save()


# 画像一覧フォーム
class Sc0104Form(forms.Form):
    category = forms.ModelChoiceField(queryset=Category.objects.exclude(category_cd=0), required=False)

    def __init__(self, *args, **kwargs):
        print(kwargs)
        super().__init__(*args, **kwargs)
        self.function_cd = "00"
        self.op_time = dTimeFormatter.format(datetime.now())
        self.category_cd = ""
        #print(self.op_time)
        logging.debug("Sc0104Form" + " - op_time=" + self.op_time)

    def clean(self):
        if self.cleaned_data['category'] is None:
            raise forms.ValidationError('')
        print("Sc0104Form.clean - category", self.cleaned_data['category'])
        return self.cleaned_data

    @property
    def filter_params(self):
        result = {}

        value = self.category_cd
        print("Sc0104Form.filter_params - value", value)
        result["category_cd"] = value

        return result

    def get_photos(self):
        photos = Photo.objects.filter(**self.filter_params).order_by('dtime', 'chome')
        return photos

ac01/views.py
import logging
from django.shortcuts import render, redirect
from django.views.generic import View
from django.views.generic import TemplateView

from ac01.forms import Sc0101Form, Sc0102Form, Sc0104Form
from ac01.query import get_photo_nextcode

# 一般会員 - index View
class IndexView(TemplateView):
    template_name: str = "index.html"


# 一般会員 - メニュー View
class Sc0101View(View):
    def get(self, request, *args, **kwargs):
        form = Sc0101Form()
        if request:
            form.function_cd = request.GET.get("function_cd") if request.GET.get("function_cd") else '00'
        return render(request, 'sc0101.html', {'form': form})

    def post(self, request, *args, **kwargs):
        logging.debug("Sc0101View" + " - request:" + str(type(request)))
        print(request)
        print(request.POST)
        form = Sc0101Form(request.POST)
        if request:
            form.function_cd = request.POST.get("function_cd") if request.POST.get("function_cd") else '00'
            logging.debug("Sc0101View.POST" + " - function_cd:" + form.function_cd)

        if form.is_valid():
            if form.function_cd == '02':
                return redirect('ac01:sc0102')
            elif form.function_cd == '04':
                return redirect('ac01:sc0104')
        return render(request, 'sc0101.html', {'form': form})


# 一般会員 - 写真投稿 View
class Sc0102View(View):
    def get(self, request, *args, **kwargs):
        form = Sc0102Form()
        logging.debug("Sc0102View.get" + " - op_time=" + form.op_time)
        if request:
            form.function_cd = request.GET.get("function_cd") if request.GET.get("function_cd") else '99'
        return render(request, 'sc0102.html', {'form': form})

    def post(self, request, *args, **kwargs):
        print(request.POST)
        if request:
            form = Sc0102Form(data=request.POST, files=request.FILES)
            form.function_cd = request.POST.get("function_cd") if request.POST.get("function_cd") else '99'
            logging.debug("Sc0102View.POST" + " - function_cd:" + form.function_cd)
        else:
            form = Sc0102Form()
        if form.function_cd == '02':
            print('is_valid 前')
            if form.is_valid():
                print('is_valid 通過')

                # プライマリーキーの設定
                dtime = form.cleaned_data['dtime']
                #dtime = 201910121800
                logging.debug("Sc0102View.POST" + " - dtime:" + str(dtime))
                yyyymm = dtime // 1000000
                nextcode = get_photo_nextcode(yyyymm)
                logging.debug("Sc0102View.POST" + " - nextid:" + str(nextcode))
                form.cleaned_data['code'] = nextcode

                print("Sc0102View.POST - form.cleaned_data:", form.cleaned_data)
                form.save()
                return redirect('ac01:sc0102')
            else:
                print(form.errors)
        else:
            return redirect('ac01:sc0101')
        return render(request, 'sc0102.html', {'form': form})

# 一般会員 - 写真一覧 View
class Sc0104View(View):
    def get(self, request, *args, **kwargs):
        print(request.GET)
        form = Sc0104Form(request.GET)
        if request:
            form.function_cd = request.GET.get("function_cd") if request.GET.get("function_cd") else '00'
            form.category_cd = request.GET.get("category") if request.GET.get("category") else ''
        logging.debug("Sc0104View.GET" + " - function_cd:" + form.function_cd)
        photos = form.get_photos() if form.is_valid() else []
        return render(request, 'sc0104.html', {'form': form, 'photos': photos})

    def post(self, request, *args, **kwargs):
        form = Sc0104Form(request.POST)
        if request:
            form.function_cd = request.POST.get("function_cd") if request.POST.get("function_cd") else '00'
            logging.debug("Sc0104View.POST" + " - function_cd:" + form.function_cd)
        if form.function_cd == '99':
            return redirect('ac01:sc0101')
        return render(request, 'sc0104.html', {'form': form, 'photos': []})

ac01/templates/index.html
<!doctype html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="refresh" content="1; ./sc0101">
<title>清瀬市冠水状況画像データベースシステム</title>
</head>
</html>

ac01/templates/sc0101.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <title>清瀬市冠水状況画像データベースシステム</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
  <script type="text/javascript" src="{% static 'js/jquery/jquery-3.4.1.slim.min.js' %}" ></script>
  <script type="text/javascript" src="{% static 'js/common.js' %}" ></script>
  <script type="text/javascript">
    //ページロード
    function sc0101Load(sender){
      commonPageLoad(sender);
    }

    //メニューボタンクリック
    function btnMenuClick(sender){
      commonFormSubmit(sender, document.frm0101);
    }
  </script>
</head>
<body onload="sc0101Load(this);">
<div class="DivBody" id="divBody">
<h1>清瀬市冠水状況画像データベースシステム</h1>
<table class="TblH2"><tr><td class="TblH2Td1">SC0101 - メニュー<td class="TblH2Td2"><span id="spnOpTime"></span></table>
<form id="frm0101" name="frm0101" method="post">
  {% csrf_token %}
  <input type="hidden" id="hdnFunctionCd" name="function_cd" value="{{ form.function_cd }}" />
  <input type="hidden" id="hdnOpTime" name="op_time" value="{{ form.op_time }}" />
  <p style="text-align:right;">

  </p>
  <p style="text-align:center;">
  <button class="ButtonMenu" id="btnMenu01" value="02" onclick="btnMenuClick(this);">写真投稿</button>
  <button class="ButtonMenu" id="btnMenu02" value="04" onclick="btnMenuClick(this);">写真一覧</button>
  </p>
</form>
</div>
</body>
</html>

ac01/templates/sc0102.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<title>清瀬市冠水状況画像データベースシステム（テスト）</title>
	<link rel="stylesheet" type="text/css" href="{% static 'js/jquery-ui/jquery-ui.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/sc0102.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery/jquery-3.4.1.slim.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui/jquery-ui.js' %}" ></script>
	<script type="text/javascript" src="{% static 'js/common.js' %}" ></script>
	<script type="text/javascript">
		//ページ・ロード
		function sc0102Load(sender){
			commonPageLoad(sender);

			$('#id_photo').change(function (e) {
				photoChanged(e);
			});

			$("#txt_entrydate").val($("#hdnDataTime").val().slice(0, 4) + "/" + $("#hdnDataTime").val().slice(4, 6) + "/" + $("#hdnDataTime").val().slice(6, 8))
			$("#sel_entrytime").val($("#hdnDataTime").val().slice(8, 12))
			$("#divDatePicker").datepicker({
				dateFormat: "yy/mm/dd",
				timepicker: true,
				step:10,
				onSelect: function(dateText, inst){
					$("#txt_entrydate").val(dateText);
					$("#divDatePicker").hide();
				},
				onMouseOut: function(){
					$("#divDatePicker").hide();
				}
			});
		}

		//画像設定
		function photoChanged(e){
			// ファイルオブジェクトを取得する
			const file = e.target.files[0];
			const reader = new FileReader();

			// アップロードした画像を設定する
			reader.onload = (function (file) {
				return function (e) {
					$('#imgPreView').attr('src', e.target.result);
					$('#imgPreView').attr('title', file.name);
				};
			})(file);

			//$('#divDropArea').css('height', '768px');
			//$('#divBody').css('height', '1600px');
			reader.readAsDataURL(file);
		}

		//DetePicker表示
		function showDatePicker(){
			$("#divDatePicker").show();
		}

		//DetePicker、マウスが外へ移動
		function divDatePickerMouseLeave(sender){
			$("#divDatePicker").hide();
		}

		//操作ボタンクリック
		function btnMenuClick(sender){
		 	if(sender.value == '02'){
		 		var entdate0 = $('#txt_entrydate').val();
		 		var entdate = entdate0.replace("/", "");
		 		while(entdate != entdate0){
		 			entdate0 = entdate;
		 			entdate = entdate0.replace("/", "");
		 		}
		 		$('#id_code').val('0000000000')
		 		$('#id_dtime').val(entdate + $('#sel_entrytime').val())
		 		$('#id_chome').val($('#selChome').val());
		 	}
		 	commonFormSubmit(sender, document.frm0102);
		}
	</script>
</head>
<body onload="sc0102Load(this)">
<div class="DivBody" id="divBody">
<h1>清瀬市冠水状況画像データベースシステム</h1>
<table class="TblH2"><tr><td class="TblH2Td1">SC0102 - 写真投稿<td class="TblH2Td2"><span id="spnOpTime"></span></table>
<form id="frm0102" name="frm0102" method="post" enctype="multipart/form-data">
    {% csrf_token %}
	<input type="hidden" id="hdnFunctionCd" name="function_cd" value="{{ form.function_cd }}" />
	<input type="hidden" id="hdnOpTime" name="op_time" value="{{ form.op_time }}" />
	{{ form.code.as_hidden }}
	{{ form.dtime.as_hidden }}
	<input type="hidden" id="hdnDataTime" name="data_time" value="{{ form.data_time }}" />
	{{ form.chome.as_hidden }}
	<table class="tblDetail">
		<tr style="height=4px"><th width="80"><th>
		<tr style="vertical-align:top;"><td colspan="2">写真を指定してください：
		{% if form.photo.errors %}
		  {{ form.photo.errors }}
		{% endif %}
		<tr style="vertical-align:top;"><td colspan="2">
			<!-- div class="DivDropArea" id="divDropArea" -->
			<div class="d-flex justify-content-center" id="divDropArea">
				{{ form.photo }}<br>
				<img id="imgPreView" style="width:100%;" >
			</div>
		<tr style="vertical-align:bottom;"><td>日時：
			<td><input type="text" required id="txt_entrydate" size="10" maxlength="10" />
				<img src="{% static 'image/dateicon.png' %}" onclick="showDatePicker()">　
				<select id="sel_entrytime">
			    	{% for sel_time in form.sel_time_list %}
						<option value="{{ sel_time.val }}">{{ sel_time.txt }}</option>
					{% endfor %}
				</select>
				<div id="divDatePicker" style="width:240px;display:none;" onmouseleave="divDatePickerMouseLeave(this);" ></div>

		<tr><td colspan="2" style="text-align:center">
			<img src="{% static 'image/KiyoseMap.png' %}">
		<tr><td>丁目：
		<td><select name="chome" id="selChome" >
			<option value="101">下宿1丁目</option>
			<option value="0102">下宿2丁目</option>
			<option value="0103">下宿3丁目</option>
			<option value="0201">旭ヶ丘1丁目</option>
			<option value="0202">旭ヶ丘2丁目</option>
			<option value="0203">旭ヶ丘3丁目</option>
			<option value="0204">旭ヶ丘4丁目</option>
			<option value="0205">旭ヶ丘5丁目</option>
			<option value="0206">旭ヶ丘6丁目</option>
			<option value="0301">中里1丁目</option>
			<option value="0302">中里2丁目</option>
			<option value="0303">中里3丁目</option>
			<option value="0304">中里4丁目</option>
			<option value="0305">中里5丁目</option>
			<option value="0306">中里6丁目</option>
			<option value="0401">野塩1丁目</option>
			<option value="0402">野塩2丁目</option>
			<option value="0403">野塩3丁目</option>
			<option value="0404">野塩4丁目</option>
			<option value="0405">野塩5丁目</option>
			<option value="0501">梅園1丁目</option>
			<option value="0502">梅園2丁目</option>
			<option value="0503">梅園3丁目</option>
			<option value="0601">竹丘1丁目</option>
			<option value="0602">竹丘2丁目</option>
			<option value="0603">竹丘3丁目</option>
			<option value="0701">松山1丁目</option>
			<option value="0702">松山2丁目</option>
			<option value="0703">松山3丁目</option>
			<option value="0801">元町1丁目</option>
			<option value="0802">元町2丁目</option>
			<option value="0901">上清戸1丁目</option>
			<option value="0902">上清戸2丁目</option>
			<option value="1001">中清戸1丁目</option>
			<option value="1002">中清戸2丁目</option>
			<option value="1003">中清戸3丁目</option>
			<option value="1004">中清戸4丁目</option>
			<option value="1005">中清戸5丁目</option>
			<option value="1101">下清戸1丁目</option>
			<option value="1102">下清戸2丁目</option>
			<option value="1103">下清戸3丁目</option>
			<option value="1104">下清戸4丁目</option>
			<option value="1105">下清戸5丁目</option>
		</select>
		<tr><td>詳細：<td>{{ form.detail }}<!--<input type="text" id="id_detail" name="detail" value="" maxlength="64" / -->
		<tr><td>会員番号：<td>{{ form.member_no }}
		{% if form.member_no.errors %}
		  {{ form.member_no.errors }}
		{% endif %}
	</table>
	<div class="DivControl">
		<button class="ButtonFunc" id="btnFunc01" value="02" onclick="btnMenuClick(this);">登録</button>
		<button class="ButtonFunc" id="btnFunc02" value="99" onclick="btnMenuClick(this);">取消</button>
	</div>
</form>
</div>
</body>
</html>

ac01/templates/sc0104.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<title>清瀬市冠水状況画像データベースシステム</title>
  	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/common.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/sc0104.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery/jquery-3.4.1.slim.min.js' %}" ></script>
	<script type="text/javascript" src="{% static 'js/common.js' %}" ></script>
	<script type="text/javascript">
		//ページロード
		function sc0104Load(sender){
			commonPageLoad(sender);
			$('#id_category').change(function (sender) {
				categoryChanged(sender);
			});
		}

		//カテゴリー選択
		function categoryChanged(sender){
			document.frm0104search.submit();
		}

		//一覧行選択
		function rdoSelectLineChange(sender){
			$('#imgPhoto').attr('src', $(sender).data('image_url'));
			// var linePhoto = "linePhoto" + sender.value;
			// $('#imgPhoto').attr('src', $('#' + linePhoto).val();)
		}

		//操作ボタンクリック
		function btnMenuClick(sender){
			commonFormSubmit(sender, document.frm0104);
		}
	</script>
</head>
<body onload="sc0104Load(this)">
<div class="DivBody" id="divBody">
<h1>清瀬市冠水状況画像データベースシステム</h1>
<table class="TblH2"><tr><td class="TblH2Td1">SC0104 - 写真一覧<td class="TblH2Td2"><span id="spnOpTime"></span></table>
<form id="frm0104Search" name="frm0104search" method="get" >
	<table class="TblControl">
		<tr><td width="60">分類：
			<td>{{ form.category }}
	</table>
</form>
	<div class="DivDataList">
		<table class="TblDataList">
			<thead>
				<tr><th width="24"><th width="120">日時<th width="100">丁目<th>詳細
			</thead>
			<tbody>
				{% for photo in photos %}
					<tr><th><input type="radio" name="selectline" value="{{ photo.id }}" data-image_url="{{ photo.photo.url }}" onchange="rdoSelectLineChange(this);" />
						<!-- input type="hidden" id="linePhoto{{ photo.id }}" value="{{ photo.photo.url }}" / -->
						<td>{{ photo.data_time }}
						<td>{{ photo.chome.chome }}
						<td style="overflow:hidden;">{{ photo.detail }}
				{% endfor %}
			</tbody>
		</table>
	</div>
	<div class="d-flex justify-content-center">
		<img id="imgPhoto" width="640">
	</div>
<form id="frm0104" name="frm0104" method="post" >
	{% csrf_token %}
	<input type="hidden" id="hdnFunctionCd" name="function_cd" value="{{ form.function_cd }}" />
	<input type="hidden" id="hdnOpTime" name="op_time" value="{{ form.op_time }}" />
	<div class="DivControl">
		<button class="ButtonFunc" id="btnFunc01" value="99" onclick="btnMenuClick(this);">戻る</button>
	</div>
</form>
</div>
</body>
</html>